### PR TITLE
Paralell

### PR DESCRIPTION
**Pull request by JesusPinedaC**
This pull request showcases the addition of the `Parallel` module. 

This new module facilitates defining parallel processing pipelines within sequential models. This feature is especially advantageous in Message Passing Networks (MPN), where dual encoders are often required—one for nodes and another for edge features. For example:

``` python
MPN = Sequential(
    Parallel(node_encoder, edge_encoder), 
    MessagePassingNeuralNetwork,
    dl.FromDict("edge_features"), # extracts the edge features
    DenseTop, # receives the edge features and yields predictions
)
```

### CODE REVIEW

**Comment by BenjaminMidtvedt** [comment]
What type of input does it work with, dict? tuples?

**Comment by JesusPinedaC** [comment]
> What type of input does it work with, dict? tuples?

This module is compatible with any input supported by Deeplay. If the input is a tensor, the parallel branches process the information and return a tuple that stores the corresponding outputs. If the input is a dictionary, it updates the keys that correspond to the output mappings specified by `set_input_map`.

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC Ok! Could we for syntactic clarity maybe have a `DictParallel(nodes=node_encoder, edges=edge_encoder)` that does the same but sets the mapping directly internally? Does it make sense or not

**Comment by JesusPinedaC** [comment]
It is actually a good idea. This way we can specify the output mapping directly in Parallel. 

But you still have to define the input mapping for `node_encoder` and `edge_encoder`. Which can be confusing for the user?

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC good point, but I think that's fine! We might add another class for doing that easily in the future

**Comment by JesusPinedaC** [comment]
I've updated the implementation as per our discussion. Now, with the new changes, we enable the usage of `ParallelDict(module1, edges=module2)`.

In this scenario, if input and output mappings are already defined for `module1`, those mappings will be respected.

If mappings are set for `module2` and a key is specified in the `Parallel` definition, the output mapping will overwrite. Similarly, if only input mapping for `module2` is set, `Parallel` will internally set the output mapping. 

This provides flexibility in defining output mapping either through an external call for `set_output_map` or by directly setting the output mapping using `Parallel`. This is particularly useful for handling multi-output modules, where it's recommended to use `set_output_map` instead of specifying the keyword. 

Additionally, `Parallel` throws an error during forward if keyword arguments are used with tensor input.

**Review by BenjaminMidtvedt — APPROVED** [review]

**Pull request merged**
