### PR TITLE
 Create Positional Embedding Layers

### PR DESCRIPTION
**Pull request by JesusPinedaC**
This pull request introduces two new DeeplayModules: `BatchedPositionalEmbedding` and `IndexedPositionalEmbedding`.

`BatchedPositionalEmbedding` implements the original positional embeddings as proposed in "Attention is All You Need". It adapts to input tensors with either `batch_first=True` or `False`.

`IndexedPositionalEmbedding` is designed for sequences of varying lengths. This layer receives two inputs, `x` and `batch_indices`. `x` is a stack of different sequences in the batch along the first dimension. `batch_indices`, in turn, contains the batch index for each sequence in the batch, facilitating the precise allocation of positional embeddings across the sequences.

### CODE REVIEW

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC Looks good! I propose we add just `PositionalEmbedding`. I think this is what people will look for first. Two ways:
### 1.
we just rename the batched one, since I think this is what most people will want

### 2. 
we use class dispatching:
```py

class PositionalEmbedding(PositionalEmbeddingBaseClass):
    def __new__(self, batched=True, dropout_p=0.0, max_length=5000, batch_first=True)
        if batched:
            return BatchedPositionalEmbedding(dropout_p=0.0, max_length=5000, batch_first=True)
        else: 
            return IndexedPositionalEmbedding(dropout_p=0.0, max_length=5000)
```

This way new users can easily dispatch to the correct version, but also create the classes directly to be more explicit

**Comment by BenjaminMidtvedt** [comment]
Actually, nevermind. I don't think 2 is a good idea. It would mess with how we do configurations and argument parsing.

**Comment by JesusPinedaC** [comment]
@BenjaminMidtvedt Agree. I've updated the implementation. 

`PositionalEmbedding` now supports batching, and `IndexedPositionalEmbedding` inherits from it, designed for cases using a `batch_indices` tensor.

Additionally, `PositionalEmbedding` can now be set to trainable. Also, Initialization options have been expanded beyond sine/cosine embeddings, supporting any method from `torch.nn.init` or custom callables.

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC Awesome! Looks great now. Can you look at the merge conflict? It's good to merge once fixed

**Comment by JesusPinedaC** [comment]
@BenjaminMidtvedt conflicts solved

**Review by BenjaminMidtvedt — APPROVED** [review]

**Pull request merged**
