### PR TITLE
Attention UNet for diffusion models

### PR DESCRIPTION
**Pull request by harbac**
This PR introduces Attention UNet for diffusion models. The model can be used for:

- DDPM models
- Conditional DDPM models,
- Text2Image DDPM models
- Image2Image DDPM models.

**Example**:

```
model = dl.AttentionUNet(
    in_channels=1,
    channels=[32, 64, 128], 
    base_channels=[256, 256],
    channel_attention=[False, False, False], # Attention can be switched on and off
    position_embedding_dim=EMBEDDING_DIM,
    num_classes = None, # Used for conditional DDPM models
    context_embedding_dim = None, # Used for text 2 image models
)
```

### CODE REVIEW

**Comment by BenjaminMidtvedt** [comment]
@HarshithBachimanchi How does this AttentionModule compare to what is already implemented? If some functionality there is lacking, would it be possible to instead extend that functionality? (Such as `MultiheadSelfAttention` etc).

**Comment by harbac** [comment]
The `AttentionBlock`  here implements basic transformer action for both self-attention and cross-attention mechanisms depending on the input given to the UNet. 

As for the comparison with`MultiheadSelfAttention` module implemented in deeplay, both the modules use the `nn.MultiheadAttention`. So, there is no direct difference both in terms of how attention mechanism is implemented. The `AttentionBlock` is 1) tailor-made to handle the inputs given to the UNet, 2) Implements the transformer actions while also handling the projections correctly.

**Comment by JesusPinedaC** [comment]
@HarshithBachimanchi @BenjaminMidtvedt I think it's fine to have two versions of attention blocks if they operate differently and serve different purposes. 

Yet, should we give it a more descriptive name? So that both implementations are differentiated.

**Comment by BenjaminMidtvedt** [comment]
@HarshithBachimanchi @JesusPinedaC I can accept this for now, but we really must start making a concerted effort to standardize our blocks. Having a specialized block for each model is sort of antithetical to the idea of deeplay and will never scale. If it is at all possible to extract the fundamental attention/transformer part of the block and use or extend existing functionality, I very strongly prefer it.

Regarding the name of the block, it should not matter too much as long as it does not clash with the name of anything already implemented. Since it's not exported into the namespace (?), the name will only ever be relevant as what will be printed in the summary.

**Comment by giovannivolpe** [comment]
I'm not sure about the specifics of this case, but in general, I think we need to make an effort to reuse already available blocks and architectures to avoid duplication. I'm also aware that this won't be possible in all cases, and sometimes it might be convenient to have some duplications to optimize the code. If needed, we can discuss this in detail in a call.

**Comment by harbac** [comment]
Hi all, Sure. Let me know which existing blocks can be used here, and suggest a scheme to incorporate them. The way I see it, the block is necessary here. There is no duplication as far I can see.

Both `MultiheadSelfAttention` and `AttentionBlock` use the `nn.MultiheadAttention` to handle the attention mechanism. The latter just builds on it to handle the inputs specific to this case. That's all. If it is the name `AttentionBlock` that is a bit perplexing, please suggest an alternate name.

**Comment by JesusPinedaC** [comment]
@HarshithBachimanchi You might consider refactoring

https://github.com/DeepTrackAI/deeplay/blob/f592b4faeaa93b092c0f819c66208e90fcb6eb10/deeplay/components/diffusion/attention_unet.py#L87-L90

to utilize `dl.LayerSkipNormalization`. It allows for more flexibility in controlling the operation order and easier reference to specific components. Like so:

``` python
layer = dl.LayerSkipNormalization(
           layer=dl.MultiheadSelfAttention(features, num_heads)
           skip=dl.Add(),
           normalization=dl.Layer(nn.LayerNorm, features),
           order=["normalization, "layer", "skip"]
 )

x = layer(x)
```

Similarly,

https://github.com/DeepTrackAI/deeplay/blob/f592b4faeaa93b092c0f819c66208e90fcb6eb10/deeplay/components/diffusion/attention_unet.py#L74-L80

(and similar operations) could be replaced with a `MultiLayerPerceptron`.


Moreover, at

https://github.com/DeepTrackAI/deeplay/blob/f592b4faeaa93b092c0f819c66208e90fcb6eb10/deeplay/components/diffusion/attention_unet.py#L149-L150

simplifying to `x = self.skip(s, emb)`, with `self.skip` being `dl.Add` by default, offers flexibility for alternative operations like concatenation.

Lastly, could we consider integrating the existing UNet component? We only replace the encoder/decoder blocks with the corresponding attention layers.

**Comment by JesusPinedaC** [comment]
@BenjaminMidtvedt @giovannivolpe what do you think?

**Comment by BenjaminMidtvedt** [comment]
@JesusPinedaC Thank you! These changes will greatly improve flexibility and scalability

**Comment by harbac** [comment]
@JesusPinedaC Thank you for suggesting! `dl.LayerSkipNormalization` can indeed be used in this case, and it does offer flexibility. These changes are still within the `AttentionBlock` however. It does not eliminate the block completely.

Regarding the existing `UNet`, It is useful for minor modifications such like adjusting the pooling layers, normalisations, and activations. More than this, there is limited flexibility. For instance, the convolution layers preceding the pooling layers are hard coded to `LazyConv2d` and there is no option to modify them to custom blocks or layers as of now. Again, let me know if I am missing something.

@BenjaminMidtvedt @giovannivolpe deeplay is still evolving, so it is challenging to have a clear picture on what can be merged, reused, or eliminated at this stage. We can address these issues as we go forward. Let me know what you think.

**Comment by BenjaminMidtvedt** [comment]
@HarshithBachimanchi 
> These changes are still within the AttentionBlock however. It does not eliminate the block completely.

That's fine, I mostly want to do as much as possible. There will need to be a revision in the near future where we homogenize everything.

 > Regarding the existing UNet, It is useful for minor modifications such like adjusting the pooling layers, normalisations, and activations. More than this, there is limited flexibility. For instance, the convolution layers preceding the pooling layers are hard coded to LazyConv2d and there is no option to modify them to custom blocks or layers as of now. Again, let me know if I am missing something.

I understand. The idea is that if something lacks the flexibility needed to expand it, we add that flexibility. The goal is to build a solid enough foundations that we don't need to make bespoke models every time. Largely, we're here because the massive time crunch we have developed deeplay under. 

I'm going to make a guideline sheet for all of this. It's my fault for not having made one yet. If something doesn't fit within the guideline, we expand it over time.

> deeplay is still evolving, so it is challenging to have a clear picture on what can be merged, reused, or eliminated at this stage. We can address these issues as we go forward. Let me know what you think.

I agree. It's very hard to balance these things. I think now deeplay is stable enough that we can start to enforce best practices. However, these do not exist yet. It's likely best to establish best practices by making a larger revision of the entire code-base. 

However, it's also much easier to say "address as we move forward" than to actually do it. My suggestion is to accept the open PRs to make a release before the course. After that, we make a concerted effort to organize and consolidate `deeplay`, establish best practices and formalize a guideline for development.

**Comment by BenjaminMidtvedt** [comment]
For this, I only need one change. I need some unittests that are based on how this will be used in the book.

These should include
1. create the models with the same arguments as you will in the book.
2. configure the models with the same arguments as you will in the book.
3. evaluate the models with the same inputs as you will in the book.

This way we know how the revision will affect the code in the book.

**Comment by harbac** [comment]
@BenjaminMidtvedt 
> That's fine, I mostly want to do as much as possible. There will need to be a revision in the near future where we homogenize everything.

Great.

> I understand. The idea is that if something lacks the flexibility needed to expand it, we add that flexibility. The goal is to build a solid enough foundations that we don't need to make bespoke models every time. Largely, we're here because the massive time crunch we have developed deeplay under.

If it is necessary, I don't think there is any harm in making bespoke models if the task at hand demands it. For example, the `AttentionUNet` was made to handle all the examples that are related to a particular chapter in the book. Not as a general model that can be re-used. 

>I'm going to make a guideline sheet for all of this. It's my fault for not having made one yet. If something doesn't fit within the guideline, we expand it over time.

That would be great.
 
>I agree. It's very hard to balance these things. I think now deeplay is stable enough that we can start to enforce best practices. However, these do not exist yet. It's likely best to establish best practices by making a larger revision of the entire code-base.

You're right. Enforce it.

> However, it's also much easier to say "address as we move forward" than to actually do it. 

Everyone will take accountability in adjusting the models they have created. I will "address" my models if there is any thing that needs to be changed as far the grammar of deeplay is concerned. And I am open to feedback on that. However, it is impossible for me or anyone else to look up into existing models, dig up bugs in them, fix them, and then use them to make models. That's just impossible. At least at this stage.

>My suggestion is to accept the open PRs to make a release before the course. After that, we make a concerted effort to organize and consolidate `deeplay`, establish best practices and formalize a guideline for development.

That would be faster. But, I am not against the idea of reusing the existing components. But if the components themselves are not perfect (for example, if their modularity does not properly fit a new model), enforcing to use them does not make any sense at this stage.

**Comment by giovannivolpe** [comment]
Ok, then I can proceed to merge it now.
We'll revise the whole code base as soon as the book is ready.

**Comment by JesusPinedaC** [comment]
@giovannivolpe unittests are still needed

**Comment by BenjaminMidtvedt** [comment]
> However, it is impossible for me or anyone else to look up into existing models, dig up bugs in them, fix them, and then use them to make models. 

The idea was more that you would create an issue addressing the limitation and suggesting a necessary new feature. Not that you would fix it yourself.

I understand this has not been possible until now because of the rapid development requirements. 

Regarding bespoke models, they're not inherently bad. But, we gain a lot but minimizing their use. It makes sure we have a cohesive and predictable interface to the user. It makes future developments easier over time since the foundeations are more flexible. 

If something is sufficiently different from established models, components or blocks, I agree we should make it bespoke. 

> But if the components themselves are not perfect (for example, if their modularity does not properly fit a new model), enforcing to use them does not make any sense at this stage.

I agree. I guess in these cases I'd more see if the new blocks/components could be generalized a little and added to the corresponding namespace (.blocks / .components) to be reused by later models. Not something we need to do now, but something that will be in the guidelines

**Comment by harbac** [comment]
By unit tests, do you mean some "automated" tests in deeplay?

If not, the models are already evaluated before I created this PR (obviously). That is, I have used this "deeplay" version of the model to run the examples in diffusion chapter and they work!

An instance of a model looks something like below. 
```
EMBEDDING_DIM = 256

model = dl.AttentionUNet(
    in_channels=1,
    channels=[32, 64, 128], # Since the image size is 28x28, we cannot use more than three channels
    base_channels=[256,256],
    channel_attention=[True, True, True],
    out_channels=1,
    position_embedding_dim=EMBEDDING_DIM,
    num_classes=10 # Additional attribute for conditional DDPM
    context_embedding_dim=768, # Additional attribute for text2image DDPM
)
```

**Comment by BenjaminMidtvedt** [comment]
@HarshithBachimanchi Yes, every PR should have it really. You can look in deeplay/tests to check how they are done. They are evaluated at every change of the code to make sure all previous functionality works as expected

**Comment by harbac** [comment]
Do you have instructions on how to create it somewhere?

**Comment by BenjaminMidtvedt** [comment]
@HarshithBachimanchi Instructions for what? 

How to make unittests? No, but it's just standard unittesting using `unittest`. Create functions that execute some code and asserts that the result is what you expect. As said, check `deeplay/tests` for examples.

What to test in the tests? Also no, though I will try create this in parallell to the guidelines. But again, as said, follow the outline I provided:

> These should include
>
>  1. create the models with the same arguments as you will in the book.
>  2. configure the models with the same arguments as you will in the book.
>  3. evaluate the models with the same inputs as you will in the book.
>
> This way we know how the revision will affect the code in the book.

**Comment by harbac** [comment]
@BenjaminMidtvedt Unit tests are added in the new commit.

**Comment by BenjaminMidtvedt** [comment]
Awesome! Looks good. I'll recommend to merge

**Review by BenjaminMidtvedt — APPROVED** [review]

**Pull request merged**
